# pre-commit: https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/crate-ci/typos
    rev: v1.31.1
    hooks:
      - id: typos

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.399
    hooks:
      - id: pyright

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.11.5
    hooks:
      # Run the linter and fix any fixable issues
      - id: ruff
        args: [ --fix ]
      # Run the formatter
      # This should be run AFTER all the code changing hooks!
      - id: ruff-format

  - repo: local
    hooks:
      - id: justfile-fmt
        name: format the justfile
        entry: just --unstable --fmt
        language: system
        files: (?i)^\.?justfile$
        pass_filenames: false
